

export const baseURL=import.meta.env.VITE_VITE_API_URL

const SummaryAPi={
    register:{
        url:'/api/user/register',
        method:'post'
    },
    login:{
        url:'/api/user/login',
        method:'post'
    },
    forgotpassword:{
        url:'/api/user/forgot-password',
        method:'put'
    },
    forgot_password_verification_otp:{
        url:"/api/user/verify-forgot-password-otp",
        method:'put'
    },
   resetpassword: {
         url:'/api/user/resetpassowrd',
         method:'put'
    },
   userDetails: {
          url:'/api/user/user-detail',
          method:'get'
    },
    logout:{
        url:"/api/user/logout",
        method:"post"
    },
    uploadAvatar:{
        url:"/api/user/upload-avatar",
        method:"put"
    },
    updateUserDetails:{
        url:"/api/user/update-user",
        method:"put"
    },
    addCategory:{
        url:'/api/category/add-category',
        method:'post'
    },
    uploadImage:{
        url:"/api/file/upload",
        method:"post"
    },
    getCategory:{
        url:"/api/category/get",
        method:'get'
    },
    updateCategory:{
        url:"/api/category/update",
        method:'put'
    },
    deleteCategory:{
        url:"/api/category/delete",
        method:"post"
    },
   createSubCategory: {
        url:'/api/subcategory/create',
        method:'post'
    },
    getSubCategory:{
        url:"/api/subcategory/get",
        method:'post'
    },
    updateSubCategory:{
        url:'/api/subcategory/update',
        method:'put'
    },
    deleteSubCategory:{
        url:'/api/subcategory/delete',
        method:'post'
    },
    createProduct:{
        url:'/api/product/create',
        method:'post'
    },
    getProduct:{
        url:'/api/product/get',
        method:'post'
    },
    getProductByCategory:{
        url:"/api/product/get-product-by-category",
        method:'post'
    },
    getProductByCategoryAndSubCategory:{
        url:"/api/product/get-product-by-category-and-subcategory",
        method:'post'
    },
    getProductDetails:{
        url:'/api/product/get-product-details',
        method:"post"
    },
     updateProductDetails:{
        url:"/api/product/update-product-details",
        method:'put'
     },
     deleteProduct:{
        url:"/api/product/delete-product",
        method:"post"
     },
     searchProduct:{
        url:'/api/product/search-product',
        method:"post"
     },
     addToCart:{
        url:'/api/cart/create',
        method:"post"
     },
     getCartItem:{
        url:'/api/cart/get',
        method:'get'
     },
     updateCartItemQty:{
        url:'/api/cart/update-qty',
        method:'put'
     },
     deleteCartItem:{
        url:'/api/cart/delete-cart-item',
        method:'post'
     },
     createAddress:{
        url:'/api/address/create',
        method:'post'
     },
     getAddress:{
        url:'/api/address/get',
        method:'get'
     },
     updateAddress:{
        url:'/api/address/update',
        method:'put'
     },
     disableAddress:{
        url:'/api/address/disable',
        method:"post"
     },
     CashOnDeliveryOrder:{
        url:"/api/order/cash-on-delivery",
        method:'post'
     },
     payment_url:{
        url:"/api/order/checkout",
        method:'post'
     },
     getOrderItems:{
        url:'/api/order/order-list',
        method:'get'
     }
     
}


export default SummaryAPi;
